### ISSUE TITLE
[Feature Request] Provide Users With a "Sing" or "Start" and "Skip" Button

### ISSUE THREAD

**Issue by ctlw83** [bhj/react-redux-starter-kit#46]
I saw some of the recent comments about push notifications to let someone know either that their time to sing has arrived or during the song prior to theirs.  However, even if someone is already in the room it might take time to shuffle around, etc.

In most KJ setups the KJ is in charge of starting/pausing the music for the next person, but what if they had the ability to start the song themselves or, if they want to skip their current turn but retain their same place in the rotation, to do that.

Feature Request Itself:
Create a "Sing/Play" and "Skip" button on singers' views.

- The Sing/Play button only becomes available when the song immediately preceding their turn is over
- - Admins have the ability to turn this feature on or off for their lobby/room in case they don't want it.
- - Admins may also need the ability to set a "lobby" or "Room" background song to fill the gap between when one song finishes and the next person clicks the "Sing" button on their device.
- The Skip Turn button is presented to singers at all times, so at any time they can skip their current place in the rotation
- - This works great with the Push notifications though.  Imagine someone is having a drink and chatting, they get notified their turn is coming up, and then they click "Skip Turn" because they want to keep chatting but also want to retain their place in the rotation.
- - The Skip Turn button allows a singer to retain their next song, but basically bumps all of their songs down the current playlist by one rotation, retaining their place in line but skipping over this current opportunity.
- - Admins have the ability to turn this feature on or off for their lobby/room in case they don't want it.
- -- Admins can also optionally set a "max skip" value, IE if a person skips 3 times, they are removed from the rotation
- -- A singer gets prompted the third time they try to skip "If you skip again you will be removed from the lobby, are you sure you still want to skip?"
- --- Yes = Remove user from lobby
- --- No = User is going to retain their current place in the rotation
- ---The counter for the amount of skips a singer used resets after they sing a song

You could also create a "leave" button that a singer can use to leave the rotation completely and remove their songs from the current playlist, although, that is probably already in the system.

**Comment by bhj** [comment]
It's an interesting idea, and the detail is appreciated!

>  if they want to skip their current turn but retain their same place in the rotation

This is indeed how it works (the queue is not first-come first-serve).

As you rightly point out, there are many possible edge cases in a party setting. Rather than adding a lot of complexity to cover specific cases, the approach we're taking is to provide the basic tools to handle most common scenarios:

- Admins and the current singer can always play/pause/skip the current song
- Previously played/skipped songs can be re-queued
- Users can make any of their queued songs their next one

Essentially, if you are skipped for any reason you are two taps away from getting back to where you were. Right now I think this is a good balance between complexity and flexibility.

**Comment by ctlw83** [comment]
Thanks for taking a look!
