### ISSUE TITLE
Queue Enhancements

### ISSUE THREAD

**Issue by 80081** [bhj/react-redux-starter-kit#49]
Firstly thanks BHJ for the work you've put into making a great Karaoke app.  Long story short I've had the opportunity to use the app a few times with small groups of friends.  I have some suggestions regards the queue that would certainly improve the usability for me and probably other people as well.

In my case I use the same room each time, more often than not there are items left in the queue from the last time.  So far as I can tell there is no ability to clear more than 1 item at a time from the queue, the only option is to delete the room and recreate it.  Ordinarily having to log out and back in again is a minor inconvenience, but if you use a smart tv as the player and have to do this via the tv's browser it's a major pain in the ass.  Surely there's justification for the admin to be able to better manage the queue, whether it be a clear all button, or a multi select and clear feature.

The other issue I've had is with monitoring the queue, a smart phone works great for people to be able to browse my library and pick the songs they want to sing, but not so much for keeping track of the queue, most phones lock themselves after a few seconds, so in order to check the queue you have to unlock it and hope you've left a tab open in the browser you can quickly re-open.  Most of my guests manage to close the tab/browser or navigate away from the page.  The only other indication for whose up next is the on screen notification, but that is at the beginning of the song which is too late if someone is not already where they need to be.  There are a few ways I think this could be improved, one way could be to have a separate /queue interface, like the player, so a separate display could be set up for the sole purpose of displaying the queue positions.  That may not be practical for most applications though, so perhaps having the queue show unobtrusively via the player down the side where it won't interfere with the lyrics, or even just briefly unobtrusively overlay via the player towards the end of a song, these could even be opt in features in the settings i.e enable queue overlay via player.

**Comment by bhj** [comment]
> In my case I use the same room each time, more often than not there are items left in the queue from the last time. So far as I can tell there is no ability to clear more than 1 item at a time from the queue, the only option is to delete the room and recreate it.

Right, "rooms" are meant to be per-session partly so that the history is preserved, and could be used to determine popular songs, etc. It's best to set finished rooms to "closed" and create a new one if possible.

> Ordinarily having to log out and back in again is a minor inconvenience, but if you use a smart tv as the player and have to do this via the tv's browser it's a major pain in the ass.

100%, changing rooms as an admin/player should be easier. I'm also thinking a "player" user that could stay logged in and be assigned to rooms would make sense.

> a separate /queue interface, like the player, so a separate display could be set up for the sole purpose of displaying the queue positions

This would be super cool! Probably should happen at the API level so any app could query this stuff.

> unobtrusively overlay via the player towards the end of a song

Agreed, now that in v1.0 the next-up singer gets "locked in", there could be an up next notification as a per-room setting. There's a lot of fun stuff that could be done with the player overlay; it's all very 1.0 currently :)

Great feedback, thanks!

**Comment by jayaranah** [comment]
Thanks for the awesome karaoke app, in the future it is better if you add a function to queue a newly downloaded song without scanning or refreshing my entire collection of songs. because if someone wants a song but not exist in my collection and I decided to download it from the internet and I need to scan again the entire existing collection before it will appear in the library search.

**Comment by bhj** [comment]
@jayaranah Thanks, and keep an eye on #27.
