### ISSUE TITLE
Few Great feature missing

### ISSUE THREAD

**Issue by noviardi1986** [bhj/react-redux-starter-kit#50]
Hi BHJ this is really great software.
Can you add replay button and toggle left right chanel for video that has karaoke and original sound track..

**Comment by bhj** [comment]
Hi and thanks :)

> Can you add replay button

Just to be clear, in the queue, if you swipe left on a song that's already been played it'll have a re-queue option. If you're referring to a button in the playback controls that would immediately restart the current song, that might be a good per-room preference. I do want to maintain the queue's "forward momentum" by default, since if someone is skipped for any reason, they are two taps away ("Re-queue" + "Make next") from getting back to where they were.

> toggle left right chanel for video that has karaoke and original sound track..

Interesting! Is this convention documented anywhere? For MP4 video it'd make more sense for the audio tracks to be in separate streams.
