### ISSUE TITLE
Metadata parsing / file format parsing does not work for Hebrew

### ISSUE THREAD

**Issue by Iddodo** [bhj/react-redux-starter-kit#53]
Almost all the songs appear under a random artist.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/56666877/210334916-1f05a45e-0a60-49b7-a976-05f7269862ca.png">

I tried deleting all local data at =~/Library/Application Support= (using macOS) and another random artist is picked.

Some songs have the artist and song name flipped for no apparent reason.

**Comment by bhj** [comment]
Hi, if your filenames are in "Title - Artist" format (rather than "Artist -Title") you can [tell the metadata parser](https://www.karaoke-eternal.com/docs/karaoke-eternal-server/#configuring-the-metadata-parser).

If the filenames still aren't parsing properly (probably an RTL language issue) but the files are correctly tagged, you can [pass the data directly to the parser](https://www.karaoke-eternal.com/faq/#my-files-have-correct-artist--title-metadata-tags-can-they-be-used-instead-of-filenames).

Let me know how it goes!
